# Generated by Django 2.1.3 on 2019-04-12 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма платежа')),
                ('datePayment', models.DateField(verbose_name='Дата платежа')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Денежные поступления',
            },
        ),
        migrations.CreateModel(
            name='ChargeUtilityBills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField(verbose_name='Статья начисления')),
                ('elect_s', models.FloatField(default='', verbose_name='Электроснабжение')),
                ('hot_weat', models.FloatField(default='', verbose_name='Подогрев воды')),
                ('cold_weat', models.FloatField(default='', verbose_name='Холодное водоснобжение')),
                ('otoplen', models.FloatField(default='', verbose_name='Отопление')),
                ('TBO', models.FloatField(default='', verbose_name='Вызов ТБО')),
                ('uborka', models.FloatField(default='', verbose_name='Уборка с места общего пользования')),
                ('amount', models.FloatField(verbose_name='Сумма платежа')),
                ('datePayment', models.DateField(verbose_name='Дата платежа')),
            ],
            options={
                'verbose_name': 'Комунальный платеж',
                'verbose_name_plural': 'Комунальные платежи',
            },
        ),
        migrations.CreateModel(
            name='CollectionToRealt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileUrl', models.ImageField(max_length=400, upload_to='', verbose_name='Путь к файлу')),
            ],
            options={
                'verbose_name': 'Коллекция фотографий',
                'verbose_name_plural': 'Коллекции фотографий',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(verbose_name='Номер кантракта')),
                ('dateContract', models.DateField(verbose_name='Дата заключения контракта')),
                ('expirationDateContract', models.DateField(verbose_name='Дата окончания контракта')),
                ('periodPaymentRent', models.DateField(verbose_name='Срок оплаты аренды')),
                ('area', models.IntegerField(verbose_name='Площадь объекта')),
                ('price', models.FloatField(verbose_name='Цена за квадрат')),
                ('status', models.TextField(default='Открыт')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operatingCost', models.FloatField(default=0, verbose_name='Эксплуатационный затраты')),
                ('etc', models.FloatField(default=0, verbose_name='Прочее')),
                ('datePayment', models.DateField(verbose_name='Дата платежа')),
            ],
            options={
                'verbose_name': 'Издержка',
                'verbose_name_plural': 'Издержки',
            },
        ),
        migrations.CreateModel(
            name='EstateObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Изображение')),
                ('city', models.TextField(max_length=100, verbose_name='Название города')),
                ('address', models.TextField(max_length=100, verbose_name='Адрес объекта')),
                ('category', models.TextField(max_length=100, verbose_name='Категория объекта')),
                ('description', models.TextField(max_length=300, verbose_name='Описание объекта')),
                ('area', models.IntegerField(verbose_name='Площадь объекта')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000, verbose_name='Текст сообщения')),
                ('date', models.DateField(verbose_name='Дата отправления')),
                ('status', models.BooleanField(default=False, verbose_name='Статус просмотра')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщение',
            },
        ),
        migrations.CreateModel(
            name='MeterReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReading', models.DateField(verbose_name='Дата снятия показаний')),
                ('electricity', models.FloatField(verbose_name='Электроэненргия')),
                ('hotWater', models.FloatField(verbose_name='Горячая вода')),
                ('coldWater', models.FloatField(verbose_name='Холодная вода')),
                ('estateObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.EstateObject', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Показание приборов',
                'verbose_name_plural': 'Показания приборов',
            },
        ),
        migrations.CreateModel(
            name='Natification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(max_length=300, verbose_name='Заголовок')),
                ('message', models.TextField(max_length=500, verbose_name='Текст сообщения')),
                ('date', models.DateField(verbose_name='Дата отправления')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeUser', models.TextField(max_length=200, verbose_name='Тип пользователя')),
                ('meneger', models.IntegerField(blank=True, default=0, verbose_name='ID Менеджера')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Tenantry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estateObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.EstateObject', verbose_name='Объект недвижимости')),
                ('tenantry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.Profile', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Арендатор',
                'verbose_name_plural': 'Арендаторы',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFile', models.FileField(upload_to='', verbose_name='Файл')),
                ('fileUrl', models.TextField(max_length=400, verbose_name='Путь к файлу')),
                ('estateObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.EstateObject', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Загруженый файл',
                'verbose_name_plural': 'Загруженные файлы',
            },
        ),
        migrations.AddField(
            model_name='natification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.Profile', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_set', to='api_v1.Profile', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_set', to='api_v1.Profile', verbose_name='Отпровитель'),
        ),
        migrations.AddField(
            model_name='estateobject',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_set', to='api_v1.Profile', verbose_name='Балансодержатель'),
        ),
        migrations.AddField(
            model_name='cost',
            name='estateObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.EstateObject', verbose_name='Объект недвижимости'),
        ),
        migrations.AddField(
            model_name='contract',
            name='estateObject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.EstateObject', verbose_name='Объект недвижимости'),
        ),
        migrations.AddField(
            model_name='contract',
            name='rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_set_contract', to='api_v1.Profile', verbose_name='Арендующий'),
        ),
        migrations.AddField(
            model_name='collectiontorealt',
            name='estateObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.EstateObject', verbose_name='Объект недвижимости'),
        ),
        migrations.AddField(
            model_name='chargeutilitybills',
            name='estateObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.EstateObject', verbose_name='Объект недвижимости'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='estateObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.EstateObject', verbose_name='Объект недвижимости'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.Profile', verbose_name='Плательщик'),
        ),
    ]
